server:
  port: 8081   # estás levantando en 8081 según el log

security:
  jwt:
    # 32+ chars. Usá algo propio y largo.
    secret: "x9Q4u2!cPZ0sG3kL7vN1wR5yT8bM2dF6hJ0aK3pR8sV1qW4z" 
    expiration-ms: 86400000  # 1 día
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/cyberguard   # ahora puerto 3307
    username: cyber
    password: Tormenta+De+Espadas+345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  # Logging Configuration
logging:
  level:
    com.socialeng.platform: DEBUG
    org.springframework.security: DEBUG

# CORS Configuration
app:
  cors:
    allowed-origins: http://localhost:3000,https://yourdomain.com

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized