server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/cyberguard   # ahora puerto 3307
    username: cyber
    password: Tormenta+De+Espadas+345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true