server:
  port: 8081   # estás levantando en 8081 según el log

jwt:
  # 🔐 Clave de al menos 256 bits. Base64 de 32 bytes = 44 chars aprox.
  secret: uKq3m7wYf8xB2e1pQ9rGz4s8V1nJ0tC6dE3hL9mA2kQ=   # ejemplo; cámbiala por una tuya
  expiration-ms: 2592000   # ej. 30 días
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/cyberguard   # ahora puerto 3307
    username: cyber
    password: Tormenta+De+Espadas+345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true